<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210225941 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA users');
        $this->addSql(<<<'SQL'
            CREATE TABLE users.address (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              uuid UUID NOT NULL,
              street VARCHAR(255) NOT NULL,
              suite VARCHAR(255) NOT NULL,
              city VARCHAR(255) NOT NULL,
              zipcode VARCHAR(255) NOT NULL,
              geo_lat VARCHAR(30) NOT NULL,
              geo_lng VARCHAR(30) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9DB48A45D17F50A6 ON users.address (uuid)');
        $this->addSql(<<<'SQL'
            CREATE TABLE users.company (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              uuid UUID NOT NULL,
              name VARCHAR(255) NOT NULL,
              catchPhrase VARCHAR(255) NOT NULL,
              bs VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DF45EC8BD17F50A6 ON users.company (uuid)');
        $this->addSql(<<<'SQL'
            CREATE TABLE users."user" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              uuid UUID NOT NULL,
              roles JSON NOT NULL,
              name VARCHAR(255) NOT NULL,
              username VARCHAR(255) NOT NULL,
              password VARCHAR(255) NOT NULL,
              email VARCHAR(255) NOT NULL,
              phone VARCHAR(30) NOT NULL,
              website VARCHAR(255) NOT NULL,
              address_id INT NOT NULL,
              company_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_86A85138D17F50A6 ON users."user" (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_86A85138F85E0677 ON users."user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_86A85138E7927C74 ON users."user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_86A85138F5B7AF75 ON users."user" (address_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_86A85138979B1AD6 ON users."user" (company_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              users."user"
            ADD
              CONSTRAINT FK_86A85138F5B7AF75 FOREIGN KEY (address_id) REFERENCES users.address (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              users."user"
            ADD
              CONSTRAINT FK_86A85138979B1AD6 FOREIGN KEY (company_id) REFERENCES users.company (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE users."user" DROP CONSTRAINT FK_86A85138F5B7AF75');
        $this->addSql('ALTER TABLE users."user" DROP CONSTRAINT FK_86A85138979B1AD6');
        $this->addSql('DROP TABLE users.address');
        $this->addSql('DROP TABLE users.company');
        $this->addSql('DROP TABLE users."user"');
    }
}
