<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260213001354 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE SCHEMA audit');
        $this->addSql('CREATE SCHEMA tasks');
        $this->addSql(<<<'SQL'
            CREATE TABLE audit.event (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              uuid UUID NOT NULL,
              type VARCHAR(255) NOT NULL,
              occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              actor_uuid UUID DEFAULT NULL,
              resource_uuid UUID DEFAULT NULL,
              payload JSON DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FC9BB034D17F50A6 ON audit.event (uuid)');
        $this->addSql(<<<'SQL'
            CREATE TABLE tasks.task (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              uuid UUID NOT NULL,
              status VARCHAR(11) DEFAULT 'To Do' NOT NULL,
              name VARCHAR(255) NOT NULL,
              description TEXT NOT NULL,
              assigned_user_uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7C23BC2CD17F50A6 ON tasks.task (uuid)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE audit.event');
        $this->addSql('DROP TABLE tasks.task');
    }
}
